### ISSUE TITLE
Some Feedback to the Bootloaders documentation

### ISSUE THREAD

**Issue by alexander-schranz** [spiral/guide#376]
I'm currently implementing serverial Template Engines into Spiral via my [PHP Templating Project](https://github.com/schranz-templating/).

First I must say I really like how Spiral Bootloader and Configuration work. Still the documentation itself was a little bit confusing for me so I want to give feedback via this issue what maybe could be improved.

# Part 1: Available Methods: Init

In https://github.com/spiral/docs/blob/3.1/docs/en/framework/bootloaders.md#available-methods

**1A**

```php
    public function init(
        EnvironmentInterface $env, 
        AbstractKernel $kernel
    ): void {
```

The `$env` and `$kernel` seems not be part of any interface. So adding maybe code comment what they are move it to a hint box:

```php
    public function init(
        EnvironmentInterface $env, // optional can be used access env variables
        AbstractKernel $kernel // optional can be used to ???
    ): void {
```

**1B**

```php
        // see "Config Objects" documentation how to create a Config class
        $this->config->setDefaults(
            QueueConfig::CONFIG,
            [
                'default' => $env->get('QUEUE_CONNECTION', 'sync'),
                // ...
            ]
        );
```

The split into BootLoader and Config Object documentation make it not easy to understand. We should definitly link here to the Config Objects docs

**1C**

```php
        $kernel->booting(function () {
            // ...
        });
```

There actually is not mention what this method is doing. Is it required to be called, need it to be called is it fine to be empty? What is the purpose of it. So it confuse a little bit here.

# Part 2: Available Methods: Boot

In https://github.com/spiral/docs/blob/3.1/docs/en/framework/bootloaders.md#available-methods

**2A**:

```php
    public function boot(
        ConfiguratorInterface $config,
        CookiesBootloader $cookies
    ): void {
        $session = $config->getConfig(SessionConfig::CONFIG);

        $cookies->whitelistCookie($session['cookie']);
    }
```

I think the first example of `boot` should more go into the direction of get something from a `Config` and creating a service depending on that configuration something like into this direction: https://github.com/schranz-templating/templating/blob/d7dc62991f29ead820ff3ef1f1db991398a5fc20/src/Integration/Spiral/Smarty/Bootloader/SmartyBootloader.php#L35-L44

It was just confusing from beginner point as I'm not understand what the code is expected todo and why I should call a method of another Bootloader. Looks something which could be an own part like configuring other packages ... But maybe just creating a service without reading from configuration so the first example of "Configuring Container" would be better from a beginner point of view. And then later go into deep about what else can be done in `boot` first how to read from the config and then how to configure other bootloaders.

**2B**:

There is missing how to access the Config object inside `bindSingleton` method. This should kind of be added I did currently:

```php
        $container->bindSingleton('smarty', function (Container $container) {
            $config = $container->get(SmartyConfig::class);

            // ...
        });
```

Which I'm not even sure if it should be this way.

-----

Hope my feedback is not to confusing. As said first I really like how Bootloader and Config works in Spiral and think they have a good well typed and developer friendly integration. Think the documentation could be little more simple to avoid confusen.

**Comment by butschster** [comment]
Thank you, @alexander-schranz !

**Comment by alexander-schranz** [comment]
@butschster nice improvements 👍 . What I did see the `$kernel->booting(` is still not documented what it is used for or what the usecase is for it.

**Comment by alexander-schranz** [comment]
Oh sorry did now see the Link to the Kernel docs 👍
