### ISSUE TITLE
Change recommendation from SQLite to MySQL

### ISSUE THREAD

**Issue by drIceman** [spiral/guide#575]
At some point, perhaps after some kind of update, when working with a Spiral project with SQLite, I ran into a problem: "General error: 1 no such savepoint: SVP0"
There wasn't much data
I tried to create the database again
Launched the app
When trying to perform migrations, another error occurred: "DB is blocked"
As a result of trying to solve these problems, I installed MySQL
And everything works great)
SQLite has many limitations
It's hard to do something complete with it
Therefore, I advise you everywhere in the documentation recommend working with something like MySQL right away
Otherwise, problems with SQLite are projected onto the framework;)

**Comment by butschster** [comment]
Hi @drIceman!

Thank you for suggestion! It's a good idea to notice that moment.
