### ISSUE TITLE
[spiral/annotated-routes] Annotated Route priority order

### ISSUE THREAD

**Issue by Phosnoiiv** [spiral/guide#605]
The framework code
https://github.com/spiral/framework/blob/b5cb7b46231e35fb48a5e7289f61d622209ce5ce/src/AnnotatedRoutes/src/RouteLocatorListener.php#L62
sorts routes so that those with lower priority come first.

The testcase also shows the route with priority -1 is matched earlier than another route with priority 0.
https://github.com/spiral/framework/blob/b5cb7b46231e35fb48a5e7289f61d622209ce5ce/src/AnnotatedRoutes/tests/App/Controller/PageController.php#L11-L25
https://github.com/spiral/framework/blob/b5cb7b46231e35fb48a5e7289f61d622209ce5ce/src/AnnotatedRoutes/tests/IntegrationTest.php#L47-L52

However the documentation https://spiral.dev/docs/http-routing/current/en#defining-routes says:
>Higher priority routes are sorted **before** lower ones.

https://github.com/spiral/docs/blob/98b4ba44cf9b5826f09c3991a1161c3dc61bdffb/docs/en/http/routing.md?plain=1#L62

After some search I find similar pattern in rr job pipelines where lower priority number means higher priority. Thus I believe the Annotated Route behavior is by design and therefore the documentation should be clarified to match the behavior. Sorry if I thought wrong.

**Comment by butschster** [comment]
Thank you @Phosnoiiv !
