### ISSUE TITLE
Link to "memory management techniques" - 404 not found

### ISSUE THREAD

**Issue by CasaMare** [spiral/guide#708]
Link in documentation 
404 - page not found

https://github.com/spiral/docs/blob/a85338b20971b019d5bd7b0ceee99ada6b31dbc5/docs/en/start/server.md?plain=1#L5

**Comment by roxblnfk** [comment]
Fixed with https://github.com/spiral/docs/commit/f9aaed50e3ba6bcb73df42ab6509f9831135fea3
